### ISSUE TITLE
No puedo facturar en producción

### ISSUE THREAD

**Issue by alanleyva** [Facturama/facturama-nodejs-sdk#1]
Todo funciona correctamente en pruebas, pero al tratar de correr en producción me sale el siguiente error en `facturama.api.js:27` al hacer console.log a err

```
error: { Error: getaddrinfo ENOTFOUND api.facturama.mx2 api.facturama.mx2:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.facturama.mx2',
  host: 'api.facturama.mx2',
  port: 443 }
```

Estoy seguro de los accesos para producción están correctos, tenemos folios disponibles y la anualidad está cubierta.
También los datos que se envían están correctos, ya que al cambiar al ambiente de pruebas no se genera ningún error.

Mi pregunta es, qué significan esos códigos de error?
Ya que no pude encontrar información por ningún lado.
También cabe mencionar que el `console.log('statusCode:', res.statusCode);` suelta un error ya que la variable `res` no existe.

```
console.log('statusCode:', res.statusCode); // Print the response status code if a response was received
^
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (.../facturama/lib/facturama.api.js:28:38)
    at self.callback (.../node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (.../node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
```

**Comment by diegordzr** [comment]
Creo que estas poniendo un 2 de mas en la url
 'api.facturama.mx**2**'

**Comment by alanleyva** [comment]
Ya funcionó

Ese "2" no lo tenía puesto en la URL 
Pero por alguna razón se arregló al ponerle una "/" al final 
Este es mi archivo de accesos final 

```

const production = true;

var valuesFacturama_Sandbox = {
  token: "tokensandbox",
  url: "https://apisandbox.facturama.mx/",
  user: "user",
  pass: "pass",
  expedition_place: "00000"
};

var valuesFacturama = {
  token: "tokenproduccion",
  url: "https://api.facturama.mx/",
  user: "user",
  pass: "pass",
  expedition_place: "00000"
};

module.exports = production ? valuesFacturama : valuesFacturama_Sandbox;

```

Ya todo parece estar funcionando correcto.
Muchas gracias!
